name: Deploy Jekyll site to Pages

on:
  # Build on every push to the default branch
  push:
    branches: ["master"]

  # Allow manual runs from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Only one Pages deploy at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby + Bundler cache
        uses: ruby/setup-ruby@v1           # ← same action, tag not pinned to a hash
        with:
          ruby-version: '3.3'              # match Gemfile.lock
          bundler-cache: true

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build \
            --baseurl "${{ steps.pages.outputs.base_path }}"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        # _site is default; no 'with:' needed

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
